version: '3'

services:
  wawebhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wawebhook
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=production
    networks:
      - wawebhook-network

networks:
  wawebhook-network:
    driver: bridge 